### ISSUE TITLE
Convert file based to MySQL based

### ISSUE THREAD

**Issue by CiprianN23** [PPC-Trucking/V1#28]
Convert the old file system to MySQL system for a better performance and data  #managment

I will do this if @CodeAlDente are agree with it. I know alot o people want this maybe on MySQL and i really want to help because its an amazing gamemode

**Comment by CodeAlDente** [comment]
I think it is a lot of work to change the system from a flat file based system to one that supports databases. Since it was never planned to be changed later on you need to consider many things in the code and the way it works (not only save and load). All in all, it is not worth that. Before you invest such a lot of time you could better create a new gamemode by using some of the functionalities from V1.

That is also what I do: Only fixing small / bigger bugs and adding features from the latest SA:MP version like vehicle colors (#15) beside some improvements which I see useful for the gamemode.

**Comment by CiprianN23** [comment]
Not that much work, i manage to convert it once(but its no more like this one)
But yeah, i suppose you are right. Not worthing at this point to convert it..
I have in mind to start another gamemode with some ideas from this..
Thanks for answer 

Have a good day :)

**Comment by CodeAlDente** [comment]
You are more than welcome to try this on your own. I do not say that it is a bad idea. The benefits of a gamemode that works with databases are huge, not only the fact you can create pretty nice user interfaces and websites where players can log-in and interact with. It is "only" the time you need to have to realize something like this.
